namespace TaskManagementSystem.Application.Enum;

public enum TaskErrorType
{
    NoError = 0,                
    ErrorGetData = 1,         
    ErrorCreateUser = 2,      
    ErrorUpdateUser = 3,       
    ErrorDeleteUser = 4,       
    ErrorUserNotFound = 5,        
    ErrorTaskStatusChange = 6, 
    ErrorAssignTask = 7,      
    ErrorReviewTask = 8,        
    ErrorAuthentication = 9,   
    ErrorAuthorization = 10,    
    ErrorDatabaseConnection = 11, 
    ErrorSystem = 12,         
    ErrorPermission = 13,
    Error = 14,
    ErrorNoTasksAvailable = 15,
    ErrorCreateTask = 16,      
    ErrorUpdateTask = 17,       
    ErrorDeleteTask = 18,
    ErrorInvalidId = 19,
    ErrorTaskNotFound = 20,
    ErrorValidation = 21,
    ErrorInvalidEmail = 22,
    ErrorInvalidCredentials = 23,
    ErrorEmailAlreadyExists = 24,
    ErrorInvalidName = 25,
    ErrorWeakPassword = 26,
    ErrorNoProjectAvailable = 27,
    ErrorCreateProject = 28,      
    ErrorUpdateProject = 29,       
    ErrorDeleteProject = 30,
    ErrorProjectNotFound = 31,
    ErrorNoMembersFound = 32,
    ErrorUnauthorizedMember = 33,
    ErrorAlreadyMember = 34,
    ErrorInvalidUsername = 35,
    ErrorUsernameIsAlreadyExist= 36,
    ErrorFriendshipNotFound = 37,
    ErrorFriendshipAlreadyExist = 38,
    ErrorInvalidOperation = 39,
    ErrorNoPendingRequests = 40
}